I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 299, in script
    e "Selamat! Kamu telah menyelesaikan semua pelajaran. Sekarang kita bisa melanjutkan ke scene selanjutnya."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 299, in script
    e "Selamat! Kamu telah menyelesaikan semua pelajaran. Sekarang kita bisa melanjutkan ke scene selanjutnya."
  File "C:\Users\user\Documents\nf\semester-4\gam\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\user\Documents\nf\semester-4\gam\renpy-8.2.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\user\Documents\nf\semester-4\gam\renpy-8.2.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
Gloo Elementary School 1.0
Fri Jun 28 18:38:50 2024
